import os
import uuid
import json
from datetime import datetime, timezone
from dotenv import load_dotenv
from flask import Flask, request, jsonify, render_template
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from groq import Groq

load_dotenv()

app = Flask(__name__)

limiter = Limiter(
    get_remote_address,
    app=app,
    default_limits=[],
    storage_uri="memory://",
)

client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

LOG_FILE = "audit_log.json"


# ── Audit log ─────────────────────────────────────────────────────────────────

def write_log(entry: dict):
    logs = read_log()
    logs.append(entry)
    with open(LOG_FILE, "w") as f:
        json.dump(logs, f, indent=2)


def read_log() -> list:
    if not os.path.exists(LOG_FILE):
        return []
    with open(LOG_FILE, "r") as f:
        return json.load(f)


# ── Signal 1: LLM Classification ─────────────────────────────────────────────

def llm_signal(text: str) -> float:
    prompt = f"""You are evaluating whether a post on a Love Island fan forum was 
written by a real human fan or generated by AI.

Real fan posts tend to be: informal, emotional, full of slang, chaotic, personal.
AI-generated posts tend to be: structured, balanced, generic, overly formal, lacking personality.

Rate the following post on a scale from 0.0 to 1.0 where:
0.0 = definitely written by a human fan
1.0 = definitely AI-generated

Respond with ONLY a number between 0.0 and 1.0. No explanation.

Post:
{text}"""

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.1,
    )
    raw = response.choices[0].message.content.strip()
    try:
        score = float(raw)
        return max(0.0, min(1.0, score))
    except ValueError:
        return 0.5
    
# ── Signal 2: Stylometric Heuristics ─────────────────────────────────────────

import re
import math

def stylometric_signal(text: str) -> float:
    sentences = [s.strip() for s in re.split(r'[.!?]+', text) if s.strip()]
    words = text.lower().split()

    if len(words) < 10 or len(sentences) < 2:
        return 0.5  # not enough text to analyze reliably

    # Metric 1: sentence length variance
    # AI text = uniform sentence lengths, human = more variable
    lengths = [len(s.split()) for s in sentences]
    mean_len = sum(lengths) / len(lengths)
    variance = sum((l - mean_len) ** 2 for l in lengths) / len(lengths)
    std_dev = math.sqrt(variance)
    # Low std_dev = uniform = more AI-like
    # Normalize: std_dev of 0 → 1.0 (AI), std_dev of 8+ → 0.0 (human)
    variance_score = max(0.0, 1.0 - (std_dev / 8.0))

    # Metric 2: type-token ratio (vocabulary diversity)
    # AI text reuses words predictably, human writing is more diverse
    unique_words = set(words)
    ttr = len(unique_words) / len(words)
    # High TTR = diverse = more human-like
    # Normalize: TTR of 1.0 → 0.0 (human), TTR of 0.5 → 1.0 (AI)
    ttr_score = max(0.0, min(1.0, (1.0 - ttr) * 2))

    # Metric 3: punctuation density
    # Human fan posts use !, ?, ... emotionally
    emotional_punct = len(re.findall(r'[!?]|\.\.\.', text))
    punct_ratio = emotional_punct / max(len(sentences), 1)
    # High emotional punctuation = more human
    # Normalize: ratio of 2+ → 0.0 (human), ratio of 0 → 1.0 (AI)
    punct_score = max(0.0, 1.0 - (punct_ratio / 2.0))

    # Combine three metrics equally
    stylometric_score = (variance_score + ttr_score + punct_score) / 3.0
    return round(stylometric_score, 3)


# ── Routes ────────────────────────────────────────────────────────────────────

@app.route("/submit", methods=["POST"])
@limiter.limit("10 per minute;100 per day")
def submit():
    data = request.get_json()
    if not data or "text" not in data or "creator_id" not in data:
        return jsonify({"error": "Missing required fields: text, creator_id"}), 400

    text = data["text"].strip()
    creator_id = data["creator_id"]

    if not text:
        return jsonify({"error": "Text cannot be empty"}), 400

    content_id = str(uuid.uuid4())
    llm_score = llm_signal(text)
    stylo_score = stylometric_signal(text)

    # Weighted combination per planning.md
    confidence = round((0.6 * llm_score) + (0.4 * stylo_score), 3)
    attribution = "likely_ai" if confidence >= 0.66 else "uncertain" if confidence >= 0.41 else "likely_human"
    label = get_label(confidence)

    entry = {
        "content_id": content_id,
        "creator_id": creator_id,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "attribution": attribution,
        "confidence": round(confidence, 3),
        "llm_score": round(llm_score, 3),
        "stylometric_score": round(stylo_score, 3),
        "status": "classified",
        "appeal_reasoning": None,
    }
    write_log(entry)

    return jsonify({
        "content_id": content_id,
        "attribution": attribution,
        "confidence": confidence,
        "label": label,
        "llm_score": round(llm_score, 3),
        "stylometric_score": round(stylo_score, 3),
    })


@app.route("/log", methods=["GET"])
def get_log():
    logs = read_log()
    return jsonify({"entries": logs[-20:]})


def get_label(confidence: float) -> str:
    if confidence >= 0.66:
        return (
            "⚠️ This post shows strong signs of AI generation. "
            "The writing lacks the personality and spontaneity "
            "we'd expect from a real Islander fan."
        )
    elif confidence >= 0.41:
        return (
            "🤔 We're not sure about this one. It could go "
            "either way. Our system isn't confident enough "
            "to make a call."
        )
    else:
        return (
            "✅ This post reads as human-written — the chaos, "
            "the slang, the passion. Verified fan energy."
        )

@app.route("/appeal", methods=["POST"])
def appeal():
    data = request.get_json()
    if not data or "content_id" not in data or "creator_reasoning" not in data:
        return jsonify({"error": "Missing required fields: content_id, creator_reasoning"}), 400

    content_id = data["content_id"]
    reasoning = data["creator_reasoning"]

    logs = read_log()
    found = False
    for entry in logs:
        if entry["content_id"] == content_id:
            entry["status"] = "under_review"
            entry["appeal_reasoning"] = reasoning
            found = True
            break

    if not found:
        return jsonify({"error": "content_id not found"}), 404

    with open(LOG_FILE, "w") as f:
        json.dump(logs, f, indent=2)

    return jsonify({
        "message": "Your appeal has been received and is under review.",
        "content_id": content_id,
        "status": "under_review"
    })

@app.route("/", methods=["GET"])
def index():
    return jsonify({
        "name": "Provenance Guard",
        "description": "AI content attribution API for creative platforms",
        "endpoints": ["/submit", "/appeal", "/log"]
    })

@app.route("/ui")
def ui():
    return render_template("index.html")

if __name__ == "__main__":
    app.run(debug=True)